-- Remove role permissions for Multi-Purpose roles
DELETE FROM "RolePermission"
WHERE "roleId" IN (
  SELECT id FROM "Role" WHERE name IN (
    'INVENTORY_MANAGER',
    'STORE_MANAGER',
    'CASHIER',
    'PURCHASING_OFFICER',
    'SALES_ASSOCIATE'
  )
);

-- Remove Multi-Purpose roles
DELETE FROM "Role"
WHERE name IN (
  'INVENTORY_MANAGER',
  'STORE_MANAGER',
  'CASHIER',
  'PURCHASING_OFFICER',
  'SALES_ASSOCIATE'
);

-- Remove Multi-Purpose permissions from other roles
DELETE FROM "RolePermission"
WHERE "permissionId" IN (
  SELECT id FROM "Permission" WHERE name IN (
    'VIEW_INVENTORY',
    'MANAGE_INVENTORY',
    'ADJUST_INVENTORY',
    'APPROVE_INVENTORY_ADJUSTMENTS',
    'VIEW_PRODUCTS',
    'MANAGE_PRODUCTS',
    'SET_PRODUCT_PRICES',
    'VIEW_SUPPLIERS',
    'MANAGE_SUPPLIERS',
    'APPROVE_SUPPLIERS',
    'CREATE_PURCHASE_ORDER',
    'APPROVE_PURCHASE_ORDER',
    'RECEIVE_INVENTORY',
    'ACCESS_POS',
    'PROCESS_SALES',
    'APPLY_DISCOUNTS',
    'VOID_SALES',
    'MANAGE_CASH_DRAWER',
    'VIEW_SALES_REPORTS',
    'VIEW_INVENTORY_REPORTS'
  )
);

-- Remove Multi-Purpose permissions
DELETE FROM "Permission"
WHERE name IN (
  'VIEW_INVENTORY',
  'MANAGE_INVENTORY',
  'ADJUST_INVENTORY',
  'APPROVE_INVENTORY_ADJUSTMENTS',
  'VIEW_PRODUCTS',
  'MANAGE_PRODUCTS',
  'SET_PRODUCT_PRICES',
  'VIEW_SUPPLIERS',
  'MANAGE_SUPPLIERS',
  'APPROVE_SUPPLIERS',
  'CREATE_PURCHASE_ORDER',
  'APPROVE_PURCHASE_ORDER',
  'RECEIVE_INVENTORY',
  'ACCESS_POS',
  'PROCESS_SALES',
  'APPLY_DISCOUNTS',
  'VOID_SALES',
  'MANAGE_CASH_DRAWER',
  'VIEW_SALES_REPORTS',
  'VIEW_INVENTORY_REPORTS'
);
